import AppKit
import Foundation
import Testing
import UniformTypeIdentifiers
@testable import ApuSeq

struct ApuSeqTests {
    @Test func parsesFASTANormalizesRowsAndInfersNucleotideKind() throws {
        let text = """
        >Beta
        AC
        GT
        >Alpha
        AC
        """

        let alignment = try AlignmentParser.parse(text)

        #expect(alignment.format == .fasta)
        #expect(alignment.length == 4)
        #expect(alignment.sequenceKind == .nucleotide)
        #expect(alignment.rows.map { $0.name } == ["Beta", "Alpha"])
        #expect(alignment.rows.map { $0.sequence } == ["ACGT", "AC--"])
    }

    @Test func parsesFASTAWithSemicolonCommentsAndWhitespaceInSequenceLines() throws {
        let text = "; generated by an upstream tool\n>Beta\nAC\tGT\n; ignored between records\n>Alpha\nA C\t\n"

        let alignment = try AlignmentParser.parse(text)

        #expect(alignment.format == .fasta)
        #expect(alignment.rows.map { $0.name } == ["Beta", "Alpha"])
        #expect(alignment.rows.map { $0.sequence } == ["ACGT", "AC--"])
    }

    @Test func parsesFASTANormalizingSequenceTextToASCIICells() throws {
        let text = """
        >Unicode name 配列
        ＡＣＧＴα
        >Plain
        ACGTA
        """

        let alignment = try AlignmentParser.parse(text)

        #expect(alignment.rows.map { $0.name } == ["Unicode name 配列", "Plain"])
        #expect(alignment.rows.map { $0.sequence } == ["ACGT?", "ACGTA"])
        #expect(alignment.length == 5)
    }

    @Test func parsesCLUSTALBlocksInOriginalSequenceOrder() throws {
        let text = """
        CLUSTAL W

        Seq1    ACGT
        Seq2    AC-T

        Seq1    TGCA
        Seq2    TG-A
        """

        let alignment = try AlignmentParser.parse(text)

        #expect(alignment.format == .clustal)
        #expect(alignment.rows.map { $0.name } == ["Seq1", "Seq2"])
        #expect(alignment.rows.map { $0.sequence } == ["ACGTTGCA", "AC-TTG-A"])
    }

    @Test func parsesCLUSTALWithConsensusLinesAndResidueCounts() throws {
        let text = """
        CLUSTAL W (1.83) multiple sequence alignment

        Seq1    ACGT--AC    6
        Seq2    AC-TGGAC    7
                ** *  **

        Seq1    TTAA    10
        Seq2    T-AA    10
                * **
        """

        let alignment = try AlignmentParser.parse(text)

        #expect(alignment.format == .clustal)
        #expect(alignment.rows.map { $0.name } == ["Seq1", "Seq2"])
        #expect(alignment.rows.map { $0.sequence } == ["ACGT--ACTTAA", "AC-TGGACT-AA"])
    }

    @Test func parsesMUSCLEAsCLUSTALStyleAlignment() throws {
        let text = """
        MUSCLE (3.8) multiple sequence alignment

        Alpha    ACGT
        Beta     A-GT
                 * **
        """

        let alignment = try AlignmentParser.parse(text)

        #expect(alignment.format == .clustal)
        #expect(alignment.rows.map { $0.name } == ["Alpha", "Beta"])
        #expect(alignment.rows.map { $0.sequence } == ["ACGT", "A-GT"])
    }

    @Test func parsesCLUSTALIgnoringHashComments() throws {
        let text = """
        CLUSTAL W
        # exported by an upstream tool

        Seq1    AC-G
        Seq2    ACGG
        # another comment
        Seq1    TT
        Seq2    T-
        """

        let alignment = try AlignmentParser.parse(text)

        #expect(alignment.format == .clustal)
        #expect(alignment.rows.map { $0.name } == ["Seq1", "Seq2"])
        #expect(alignment.rows.map { $0.sequence } == ["AC-GTT", "ACGGT-"])
    }

    @Test func rejectsCLUSTALHeaderWithoutSequenceRows() throws {
        #expect(throws: AlignmentParseError.unsupportedFormat) {
            try AlignmentParser.parse("CLUSTAL W\n\n        *:*:\n")
        }
    }

    @Test func serializesRowsAsFASTAAndCLUSTAL() {
        let rows = [
            AlignmentRow(name: "Seq 1", sequence: "ACGT"),
            AlignmentRow(name: "Seq2", sequence: "A-GT")
        ]

        let fasta = AlignmentSerializer.serialize(rows: rows, preferredFormat: .fasta)
        let clustal = AlignmentSerializer.serialize(rows: rows, preferredFormat: .clustal)

        #expect(fasta == ">Seq 1\nACGT\n>Seq2\nA-GT\n")
        #expect(clustal.hasPrefix("CLUSTAL\n\n"))
        #expect(clustal.contains("Seq_1"))
        #expect(clustal.contains("A-GT"))
    }

    @Test func serializesRowsAsPlainTextSequencesOnly() {
        let rows = [
            AlignmentRow(name: "Seq 1", sequence: "ACGT"),
            AlignmentRow(name: "Seq2", sequence: "A-GT")
        ]

        let plainText = AlignmentSerializer.serialize(rows: rows, preferredFormat: .plainText)

        #expect(plainText == "ACGT\nA-GT\n")
    }

    @Test func exportsSelectedColumnsAsFASTAByDisplayedRow() {
        let text = "ACGT\nA-GT\n"
        let fasta = AlignmentSelectionExporter.selectedFASTAString(
            text: text,
            rowNames: ["Alpha", "Beta"],
            alignmentLength: 4,
            selectedRanges: [
                NSRange(location: 1, length: 2),
                NSRange(location: 6, length: 2)
            ]
        )

        #expect(fasta == ">Alpha [2-3]\nCG\n>Beta [2-3]\n-G\n")
    }

    @Test func exportsSelectedFASTAIgnoringNewlinesAndEmptySelections() {
        let text = "ACGT\nA-GT\n"
        let fasta = AlignmentSelectionExporter.selectedFASTAString(
            text: text,
            rowNames: ["Alpha", "Beta"],
            alignmentLength: 4,
            selectedRanges: [
                NSRange(location: 3, length: 4)
            ]
        )

        #expect(fasta == ">Alpha [4-4]\nT\n>Beta [1-2]\nA-\n")
        #expect(AlignmentSelectionExporter.selectedFASTAString(
            text: text,
            rowNames: ["Alpha", "Beta"],
            alignmentLength: 4,
            selectedRanges: [NSRange(location: 0, length: 0)]
        ) == nil)
    }

    @Test func parsesPlainTextRemovingWhitespaceWithinSequenceLines() throws {
        let alignment = try AlignmentParser.parse("AC GT\nA\t-GT\n")

        #expect(alignment.format == .plainText)
        #expect(alignment.rows.map { $0.sequence } == ["ACGT", "A-GT"])
    }

    @Test func reverseComplementPreservesNamesAndHandlesAmbiguousBases() throws {
        let text = """
        >Mixed
        ACGTURYKMBVDH-.acgt
        """

        let output = try AlignmentReverseComplementer.reverseComplementFASTA(rawText: text)

        #expect(output == ">Mixed\nacgt.-DHBVKMRYAACGT")
    }

    @Test func reverseComplementExplicitlyHandlesIUPACSelfComplementAndUnknownBases() throws {
        let text = """
        >IUPAC
        SWNsvnA?T
        """

        let output = try AlignmentReverseComplementer.reverseComplementFASTA(rawText: text)

        #expect(output == ">IUPAC\nA?TnbsNWS")
    }

    @Test func reverseComplementRejectsAminoAcidAlignments() throws {
        let text = """
        >Protein
        MPEPTIDE
        """

        #expect(throws: AlignmentReverseComplementError.unsupportedSequenceKind) {
            try AlignmentReverseComplementer.reverseComplementFASTA(rawText: text)
        }
    }

    @Test func translatesNucleotideFASTAWithFramesAndCodonTables() throws {
        let text = """
        >Coding
        ATGAAATGATAACTTTGAATAAGAAGG
        """

        let standard = try AlignmentTranslator.translateFASTA(
            rawText: text,
            frameOffset: 0,
            codonTable: .standard
        )
        let vertebrateMitochondrial = try AlignmentTranslator.translateFASTA(
            rawText: text,
            frameOffset: 0,
            codonTable: .vertebrateMitochondrial
        )
        let yeastMitochondrial = try AlignmentTranslator.translateFASTA(
            rawText: text,
            frameOffset: 0,
            codonTable: .yeastMitochondrial
        )
        let moldProtozoanMitochondrial = try AlignmentTranslator.translateFASTA(
            rawText: text,
            frameOffset: 0,
            codonTable: .moldProtozoanMitochondrial
        )
        let invertebrateMitochondrial = try AlignmentTranslator.translateFASTA(
            rawText: text,
            frameOffset: 0,
            codonTable: .invertebrateMitochondrial
        )
        let bacterialArchaealPlastid = try AlignmentTranslator.translateFASTA(
            rawText: text,
            frameOffset: 0,
            codonTable: .bacterialArchaealPlastid
        )
        let shifted = try AlignmentTranslator.translateFASTA(
            rawText: text,
            frameOffset: 1,
            codonTable: .standard
        )

        #expect(standard == ">Coding\nMK**L*IRR")
        #expect(vertebrateMitochondrial == ">Coding\nMKW*LWM**")
        #expect(yeastMitochondrial == ">Coding\nMKW*TWMRR")
        #expect(moldProtozoanMitochondrial == ">Coding\nMKW*LWIRR")
        #expect(invertebrateMitochondrial == ">Coding\nMKW*LWMSS")
        #expect(bacterialArchaealPlastid == standard)
        #expect(shifted == ">Coding\n*NDNFE*E")
    }

    @Test func translatedCodingSequenceKeepsSourceCodons() throws {
        let translated = try AlignmentTranslator.translatedCodingSequence(
            "ATG-AAR-TTY",
            sequenceName: "Coding",
            frameOffset: 0,
            codonTable: .standard,
            requiresCompleteCodons: true
        )

        #expect(translated.aminoAcids == "MXX")
        #expect(translated.codons == ["ATG", "AAR", "TTY"])
    }

    @Test func translatedCodingSequenceRejectsIncompleteCodonsWhenRequired() throws {
        do {
            _ = try AlignmentTranslator.translatedCodingSequence(
                "ATGAA",
                sequenceName: "Coding",
                frameOffset: 0,
                codonTable: .standard,
                requiresCompleteCodons: true
            )
            Issue.record("Expected incomplete codon error")
        } catch AlignmentTranslationError.incompleteCodon(let sequenceName) {
            #expect(sequenceName == "Coding")
        } catch {
            Issue.record("Unexpected error: \(error)")
        }
    }

    @Test func aminoAcidGuidedBackMapRestoresCodonGaps() throws {
        let nucleotide = try AminoAcidGuidedNucleotideAligner.backMapCodons(
            alignedAminoAcidSequence: "M-KF",
            codons: ["ATG", "AAA", "TTT"],
            sequenceName: "Coding"
        )

        #expect(nucleotide == "ATG---AAATTT")
    }

    @Test func aminoAcidGuidedBackMapRejectsUnusedCodons() throws {
        do {
            _ = try AminoAcidGuidedNucleotideAligner.backMapCodons(
                alignedAminoAcidSequence: "M-",
                codons: ["ATG", "AAA"],
                sequenceName: "Coding"
            )
            Issue.record("Expected codon mapping error")
        } catch AminoAcidGuidedNucleotideAlignmentError.codonMappingFailed(let sequenceName) {
            #expect(sequenceName == "Coding")
        } catch {
            Issue.record("Unexpected error: \(error)")
        }
    }

    @Test func aminoAcidGuidedAlignmentPreservesStopCodons() async throws {
        let rawText = """
        >seq1
        ATGTAAATG
        >seq2
        ATGTAGATG
        """

        let aligned = try await AminoAcidGuidedNucleotideAligner.align(
            rawText: rawText,
            frameOffset: 0,
            codonTable: .standard
        )

        #expect(aligned.contains("ATGTAAATG"))
        #expect(aligned.contains("ATGTAGATG"))
    }

    @Test func textDecodingReadsUTF8UTF16AndShiftJIS() throws {
        let utf8Data = Data("ACGT".utf8)
        let utf16Data = try #require("ACGT".data(using: .utf16LittleEndian))
        let shiftJISData = try #require("配列".data(using: .shiftJIS))

        #expect(TextDecoding.decode(utf8Data) == "ACGT")
        #expect(TextDecoding.decode(utf16Data) == "ACGT")
        #expect(TextDecoding.decode(shiftJISData) == "配列")
    }

    @Test func consensusIgnoresGapsAndFallsBackToGapForEmptyColumns() {
        let rows = [
            AlignmentRow(name: "A", sequence: "A-C"),
            AlignmentRow(name: "B", sequence: "AT-"),
            AlignmentRow(name: "C", sequence: "A--")
        ]

        let consensus = AlignmentStatistics.consensusSequence(rows: rows, length: 3)

        #expect(consensus == "ATC")
    }

    @Test func rendererComputesIdentityAndMajorityResiduesWhenRequested() throws {
        let rows = [
            AlignmentRow(name: "A", sequence: "ACG"),
            AlignmentRow(name: "B", sequence: "ATG"),
            AlignmentRow(name: "C", sequence: "A-G")
        ]
        let alignment = AlignmentData(format: .fasta, rows: rows, length: 3, sequenceKind: .nucleotide)

        let rendered = AlignmentRenderer.render(
            alignment,
            needsIdentityByColumn: true,
            needsMajorityResidueByColumn: true,
            fontSize: 12
        )

        #expect(rendered.identityByColumn.count == 3)
        #expect(abs(rendered.identityByColumn[0] - 1.0) < 0.001)
        #expect(abs(rendered.identityByColumn[1] - (1.0 / 3.0)) < 0.001)
        #expect(abs(rendered.identityByColumn[2] - 1.0) < 0.001)
        #expect(rendered.majorityResidueByColumn.compactMap(UnicodeScalar.init).map(String.init) == ["A", "C", "G"])
    }

    @Test func rendererSkipsColumnStatisticsWhenBackgroundDoesNotNeedThem() {
        let rows = [
            AlignmentRow(name: "A", sequence: "ACG"),
            AlignmentRow(name: "B", sequence: "ATG")
        ]
        let alignment = AlignmentData(format: .fasta, rows: rows, length: 3, sequenceKind: .nucleotide)

        let rendered = AlignmentRenderer.render(
            alignment,
            needsIdentityByColumn: false,
            needsMajorityResidueByColumn: false,
            fontSize: 12
        )

        #expect(rendered.identityByColumn.isEmpty)
        #expect(rendered.majorityResidueByColumn.isEmpty)
    }

    @Test func rendererUsesMeasuredNameColumnWidth() {
        let fontSize = 18.0
        let name = "Wide Sequence Name"
        let alignment = AlignmentData(
            format: .fasta,
            rows: [AlignmentRow(name: name, sequence: "ACGT")],
            length: 4,
            sequenceKind: .nucleotide
        )

        let rendered = AlignmentRenderer.render(
            alignment,
            needsIdentityByColumn: false,
            needsMajorityResidueByColumn: false,
            fontSize: fontSize
        )

        let font = NSFont.monospacedSystemFont(ofSize: fontSize, weight: .regular)
        let attributes: [NSAttributedString.Key: Any] = [.font: font]
        let nameWidth = (name as NSString).size(withAttributes: attributes).width
        let expectedWidth = ceil(nameWidth + (("M" as NSString).size(withAttributes: attributes).width * 2) + 20)
        #expect(rendered.nameColumnWidth == expectedWidth)
    }

    @Test func editingReplacementAllowsOnlyPrintableASCIICharacters() {
        #expect(AlignmentSequenceInput.isValidEditingReplacement(""))
        #expect(AlignmentSequenceInput.isValidEditingReplacement("ACGT-.*?"))
        #expect(!AlignmentSequenceInput.isValidEditingReplacement("AC GT"))
        #expect(!AlignmentSequenceInput.isValidEditingReplacement("AC\nGT"))
        #expect(!AlignmentSequenceInput.isValidEditingReplacement("ＡCGT"))
        #expect(!AlignmentSequenceInput.isValidEditingReplacement("ACGT😀"))
    }

    @Test func referenceDifferenceColoringNormalizesCaseAndGapCharacters() {
        #expect(ReferenceDifferencePalette.backgroundColor(for: 65, referenceResidue: 65) == nil)
        #expect(ReferenceDifferencePalette.backgroundColor(for: 97, referenceResidue: 65) == nil)
        #expect(ReferenceDifferencePalette.backgroundColor(for: 46, referenceResidue: 45) == nil)
        #expect(ReferenceDifferencePalette.backgroundColor(for: 67, referenceResidue: 65) != nil)
        #expect(ReferenceDifferencePalette.backgroundColor(for: 67, referenceResidue: nil) == nil)
    }

    @Test func upgmaOrderingGroupsMostSimilarRows() throws {
        let rows = [
            AlignmentRow(name: "Distant", sequence: "TTTT"),
            AlignmentRow(name: "Reference", sequence: "AAAA"),
            AlignmentRow(name: "Similar", sequence: "AAAT")
        ]

        let orderedNames = AlignmentClusterer.upgmaOrderedRows(rows).map { $0.name }

        let referenceIndex = try #require(orderedNames.firstIndex(of: "Reference"))
        let similarIndex = try #require(orderedNames.firstIndex(of: "Similar"))
        #expect(abs(referenceIndex - similarIndex) == 1)
    }

    @Test func rowOrderingSortsNamesUsingLocalizedStandardCompare() {
        let rows = [
            AlignmentRow(name: "sample 10", sequence: "AAAA"),
            AlignmentRow(name: "sample 2", sequence: "CCCC"),
            AlignmentRow(name: "sample 1", sequence: "GGGG")
        ]

        let orderedRows = AlignmentRowOrdering.nameOrderedRows(rows)

        #expect(orderedRows.map { $0.name } == ["sample 1", "sample 2", "sample 10"])
    }

    @Test func upgmaOrderingIsLimitedToThreeThroughThreeHundredRows() {
        let twoRows = (0..<2).map { AlignmentRow(name: "Row \($0)", sequence: "AC") }
        let threeHundredRows = (0..<300).map { AlignmentRow(name: "Row \($0)", sequence: "AC") }
        let threeHundredOneRows = (0..<301).map { AlignmentRow(name: "Row \($0)", sequence: "AC") }

        #expect(!AlignmentRowOrdering.canOrderWithUPGMA(rowCount: twoRows.count))
        #expect(AlignmentRowOrdering.canOrderWithUPGMA(rowCount: threeHundredRows.count))
        #expect(!AlignmentRowOrdering.canOrderWithUPGMA(rowCount: threeHundredOneRows.count))
        #expect(AlignmentRowOrdering.upgmaOrderedRows(threeHundredOneRows).map { $0.name } == threeHundredOneRows.map { $0.name })
    }

    @Test func allGapColumnRemovalRemovesOnlySharedGapColumns() throws {
        let rows = [
            AlignmentRow(name: "A", sequence: "A-.C"),
            AlignmentRow(name: "B", sequence: "T--G"),
            AlignmentRow(name: "C", sequence: "C-.T")
        ]

        let editedRows = try #require(AlignmentColumnEditor.removingAllGapColumns(from: rows, length: 4))

        #expect(editedRows.map { $0.name } == ["A", "B", "C"])
        #expect(editedRows.map { $0.sequence } == ["AC", "TG", "CT"])
    }

    @Test func allGapColumnRemovalLeavesNoOpAndAllGapAlignmentsUnchanged() {
        let noGapRows = [
            AlignmentRow(name: "A", sequence: "AC"),
            AlignmentRow(name: "B", sequence: "TG")
        ]
        let allGapRows = [
            AlignmentRow(name: "A", sequence: "-."),
            AlignmentRow(name: "B", sequence: "--")
        ]

        #expect(AlignmentColumnEditor.removingAllGapColumns(from: noGapRows, length: 2) == nil)
        #expect(AlignmentColumnEditor.removingAllGapColumns(from: allGapRows, length: 2) == nil)
    }

    @Test func trailingGapTrimRemovesOnlyTerminalGapCharacters() throws {
        let rows = [
            AlignmentRow(name: "A", sequence: "AC--"),
            AlignmentRow(name: "B", sequence: "A-C."),
            AlignmentRow(name: "C", sequence: "--AC")
        ]

        #expect(AlignmentColumnEditor.hasTrailingGaps(in: rows))
        let trimmedRows = try #require(AlignmentColumnEditor.trimmingTrailingGaps(from: rows))

        #expect(trimmedRows.map { $0.name } == ["A", "B", "C"])
        #expect(trimmedRows.map { $0.sequence } == ["AC", "A-C", "--AC"])
    }

    @Test func trailingGapTrimReturnsNilWhenNoRowsChange() {
        let rows = [
            AlignmentRow(name: "A", sequence: "AC"),
            AlignmentRow(name: "B", sequence: "-C")
        ]

        #expect(!AlignmentColumnEditor.hasTrailingGaps(in: rows))
        #expect(AlignmentColumnEditor.trimmingTrailingGaps(from: rows) == nil)
    }

    @Test func rowOnlyEditPadsAtRowEndsWithoutChangingOtherColumns() throws {
        let edited = try #require(
            AlignmentColumnEditor.replacingRowsOnly(
                in: ["ACGT", "ACGT"],
                edits: [
                    AlignmentColumnEditor.RowEdit(row: 1, column: 2, length: 0, replacement: "-")
                ]
            )
        )

        #expect(edited.length == 5)
        #expect(edited.sequences == ["ACGT-", "AC-GT"])
    }

    @Test func rowOnlyDeletionPadsEditedRowAtEnd() throws {
        let edited = try #require(
            AlignmentColumnEditor.replacingRowsOnly(
                in: ["ACGT", "A-GT"],
                edits: [
                    AlignmentColumnEditor.RowEdit(row: 1, column: 1, length: 1, replacement: "")
                ]
            )
        )

        #expect(edited.length == 4)
        #expect(edited.sequences == ["ACGT", "AGT-"])
    }

    @Test func gapColumnInsertionAddsGapToEveryRowAtColumn() throws {
        let rows = [
            AlignmentRow(name: "A", sequence: "ACGT"),
            AlignmentRow(name: "B", sequence: "A-GT")
        ]

        let editedRows = try #require(AlignmentColumnEditor.insertingGapColumn(in: rows, column: 2))

        #expect(editedRows.map { $0.name } == ["A", "B"])
        #expect(editedRows.map { $0.sequence } == ["AC-GT", "A--GT"])
    }

    @Test func selectedColumnRealignmentRestoresOnlySelectedRegion() async throws {
        let rows = [
            AlignmentRow(name: "A", sequence: "AAAC-CGG"),
            AlignmentRow(name: "B", sequence: "AAA---GG"),
            AlignmentRow(name: "C", sequence: "AAATTTGG")
        ]

        let realignedRows = try await AlignmentRangeRealigner.realignSelectedColumns(
            rows: rows,
            columnRange: 3..<6
        ) { rows in
            #expect(rows == [
                AlignmentRow(name: "ApuSeq_Row_0", sequence: "CC"),
                AlignmentRow(name: "ApuSeq_Row_2", sequence: "TTT")
            ])
            return [
                AlignmentRow(name: "ApuSeq_Row_0", sequence: "C-C-"),
                AlignmentRow(name: "ApuSeq_Row_2", sequence: "TT-T")
            ]
        }

        #expect(realignedRows == [
            AlignmentRow(name: "A", sequence: "AAAC-C-GG"),
            AlignmentRow(name: "B", sequence: "AAA----GG"),
            AlignmentRow(name: "C", sequence: "AAATT-TGG")
        ])
    }

    @Test func selectedColumnRealignmentRejectsInsufficientNonEmptyRows() async throws {
        let rows = [
            AlignmentRow(name: "A", sequence: "AAA---GG"),
            AlignmentRow(name: "B", sequence: "AAAC--GG")
        ]

        do {
            _ = try await AlignmentRangeRealigner.realignSelectedColumns(
                rows: rows,
                columnRange: 3..<6
            ) { rows in
                rows
            }
            Issue.record("Expected selected column realignment to reject one non-empty selected fragment")
        } catch AlignmentRangeRealignmentError.insufficientNonEmptyRows {
        } catch {
            Issue.record("Unexpected error: \(error)")
        }
    }

    @Test @MainActor func viewModelRendersNameOrderWithoutChangingOriginalAlignment() async throws {
        let viewModel = AlignmentViewModel()
        viewModel.alignment = AlignmentData(
            format: .fasta,
            rows: [
                AlignmentRow(name: "sample 10", sequence: "AAAA"),
                AlignmentRow(name: "sample 2", sequence: "CCCC"),
                AlignmentRow(name: "sample 1", sequence: "GGGG")
            ],
            length: 4,
            sequenceKind: .nucleotide
        )

        viewModel.rerender(
            fontSize: 12,
            needsIdentityByColumn: false,
            needsMajorityResidueByColumn: false,
            displayOrderMode: .name,
            referenceName: nil
        )
        try await waitUntil { viewModel.contentVersion > 0 }

        #expect(viewModel.displayedRows.map { $0.name } == ["sample 1", "sample 2", "sample 10"])
        #expect(viewModel.alignment.rows.map { $0.name } == ["sample 10", "sample 2", "sample 1"])
        #expect(viewModel.renderedDisplayOrderMode == .name)
    }

    @Test func documentSnapshotReturnsCurrentRawText() throws {
        let rawText = ">Seq1\nACGT\n"
        let document = ApuSeqDocument(rawText: rawText)

        let snapshot = try document.snapshot(contentType: .plainText)

        #expect(snapshot == rawText)

        document.rawText = ">Seq2\nTGCA\n"
        #expect(try document.snapshot(contentType: .plainText) == ">Seq2\nTGCA\n")
    }

    @Test func documentInitializesGeneratedRawTextWithoutMutation() throws {
        let rawText = ">Translated\nMK*"
        let document = ApuSeqDocument(rawText: rawText)

        #expect(try document.snapshot(contentType: .plainText) == rawText)
    }

    @Test func identityBarsUseSharedHeightEncoding() {
        let bars = IdentityBars.barString(from: [0.0, 0.125, 0.5, 1.0])

        #expect(bars == " ▁▄█")
    }

    @Test func printLayoutWrapsColumnsAndRowsIntoPages() {
        let rows = (0..<5).map { index in
            AlignmentRow(name: "Seq \(index)", sequence: String(repeating: "A", count: 130))
        }
        let alignment = AlignmentData(
            format: .fasta,
            rows: rows,
            length: 130,
            sequenceKind: .nucleotide
        )
        let pages = AlignmentPrintLayout.pages(
            alignment: alignment,
            options: AlignmentPrintOptions(maximumColumnsPerBlock: 100, includesConsensus: true, includesIdentity: true),
            pageContentSize: CGSize(width: 250, height: 120),
            nameColumnWidth: 80,
            characterWidth: 5,
            lineHeight: 12
        )

        #expect(pages.first?.columnRange == 0..<31)
        #expect(pages.first?.rowRange == 0..<1)
        #expect(pages.count == 25)
    }

    @Test func printLayoutDefaultUsesAvailableWidthWithoutColumnCap() {
        let rows = [
            AlignmentRow(name: "Seq 0", sequence: String(repeating: "A", count: 160))
        ]
        let alignment = AlignmentData(
            format: .fasta,
            rows: rows,
            length: 160,
            sequenceKind: .nucleotide
        )
        let pages = AlignmentPrintLayout.pages(
            alignment: alignment,
            options: .default,
            pageContentSize: CGSize(width: 620, height: 160),
            nameColumnWidth: 80,
            characterWidth: 5,
            lineHeight: 12
        )

        #expect(pages.first?.columnRange == 0..<105)
        #expect(pages.count == 2)
    }

    @Test func printLayoutFallsBackToOneColumnForInvalidCharacterWidth() {
        let columnsPerBlock = AlignmentPrintLayout.resolvedColumnsPerBlock(
            maximumColumnsPerBlock: Int.max,
            pageContentWidth: 620,
            nameColumnWidth: 80,
            characterWidth: 0
        )

        #expect(columnsPerBlock == 1)
    }

    @Test func printLayoutIncludesReferenceAuxiliaryLine() {
        let rows = (0..<5).map { index in
            AlignmentRow(name: "Seq \(index)", sequence: String(repeating: "A", count: 60))
        }
        let alignment = AlignmentData(
            format: .fasta,
            rows: rows,
            length: 60,
            sequenceKind: .nucleotide
        )
        let pagesWithoutReference = AlignmentPrintLayout.pages(
            alignment: alignment,
            options: AlignmentPrintOptions(maximumColumnsPerBlock: 100, includesConsensus: true, includesIdentity: true),
            pageContentSize: CGSize(width: 500, height: 145),
            nameColumnWidth: 80,
            characterWidth: 5,
            lineHeight: 12
        )
        let pagesWithReference = AlignmentPrintLayout.pages(
            alignment: alignment,
            options: AlignmentPrintOptions(
                maximumColumnsPerBlock: 100,
                referenceName: "Seq 0",
                referenceSequence: rows[0].sequence,
                includesConsensus: true,
                includesIdentity: true
            ),
            pageContentSize: CGSize(width: 500, height: 145),
            nameColumnWidth: 80,
            characterWidth: 5,
            lineHeight: 12
        )

        #expect(pagesWithoutReference.count == 3)
        #expect(pagesWithReference.count == 5)
    }

    @Test func printInfoUsesClippingPaginationForViewManagedPages() {
        let printInfo = AlignmentPrinter.configuredPrintInfo()

        #expect(printInfo.horizontalPagination == .clip)
        #expect(printInfo.verticalPagination == .clip)
        #expect(!printInfo.isHorizontallyCentered)
        #expect(!printInfo.isVerticallyCentered)
    }

    @MainActor
    @Test func printPanelKeepsStandardScaleAndAddsApuSeqFontSizeAccessory() {
        let printPanel = AlignmentPrinter.configuredPrintPanel(settings: AlignmentPrintSettings(fontSize: 9))

        #expect(printPanel.options.contains(.showsPreview))
        #expect(printPanel.options.contains(.showsScaling))
        #expect(printPanel.options.contains(.showsPageSetupAccessory))
        #expect(printPanel.accessoryControllers.contains { $0 is AlignmentPrintAccessoryController })
        let steppers = printPanel.accessoryControllers
            .flatMap { $0.view.allDescendants(ofType: NSStepper.self) }
        #expect(steppers.contains { !$0.valueWraps })
    }

    @MainActor
    @Test func printViewUsesPrintInfoMarginsForPrintableSize() {
        let printInfo = NSPrintInfo()
        printInfo.paperSize = NSSize(width: 595, height: 842)
        printInfo.leftMargin = 36
        printInfo.rightMargin = 36
        printInfo.topMargin = 36
        printInfo.bottomMargin = 36

        let size = AlignmentPrintView.printablePageSize(for: printInfo)
        let expectedWidth = printInfo.paperSize.width - printInfo.leftMargin - printInfo.rightMargin
        let expectedHeight = printInfo.paperSize.height - printInfo.topMargin - printInfo.bottomMargin

        #expect(size.width > 0)
        #expect(size.height > 0)
        #expect(size.width <= expectedWidth)
        #expect(size.height <= expectedHeight)
    }

    @MainActor
    @Test func printMetricsUsesPrintFontSizeForTextMetrics() {
        let smallMetrics = AlignmentPrintMetrics(fontSize: 6.75)
        let largeMetrics = AlignmentPrintMetrics(fontSize: 13.5)

        #expect(smallMetrics.baseFont.pointSize == 6.75)
        #expect(largeMetrics.baseFont.pointSize == 13.5)
        #expect(smallMetrics.characterWidth < largeMetrics.characterWidth)
        #expect(smallMetrics.lineHeight < largeMetrics.lineHeight)
    }

    @MainActor
    private func waitUntil(
        timeout: Duration = .seconds(2),
        condition: @MainActor @escaping () -> Bool
    ) async throws {
        let start = ContinuousClock.now
        while !condition() {
            if ContinuousClock.now - start > timeout {
                Issue.record("Timed out waiting for asynchronous rendering")
                return
            }
            try await Task.sleep(for: .milliseconds(10))
        }
    }
}

private extension NSView {
    func allDescendants<ViewType: NSView>(ofType type: ViewType.Type) -> [ViewType] {
        subviews.flatMap { subview in
            var matches = subview.allDescendants(ofType: type)
            if let matchingSubview = subview as? ViewType {
                matches.insert(matchingSubview, at: 0)
            }
            return matches
        }
    }
}
